services:
  trame:
    image: pytrame
    container_name: pytrame
    restart: unless-stopped
    env_file:
      - .env

    ports:
      - 8082:80

networks:
  default:
    name: horizon_network
    external: true
